spring.application.name=Hehe

# Server Port
server.port=${SERVER_PORT:8080}

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:warehouse_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Custom JWT Config (Will be read in Security Config)
jwt.secret=${JWT_SECRET:ChucNangQuanLyKhoHangNhieuChiNhanhDuAnTotNghiep2026SuperSecretKey}
jwt.expiration=${JWT_EXPIRATION:86400000}

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
