package com.example.Hehe.model;

public enum ReceiptStatus {
    DRAFT,
    PENDING_STAFF_CONFIRM,
    PENDING_ADMIN,
    PENDING_STOCKTAKE,
    PENDING_SHORTFALL_MANAGER,
    PENDING_SHORTFALL_ADMIN,
    PENDING_COMPENSATION,
    COMPLETED,
    CANCELLED,
    RETURN
}
